[build]
    command = "npm run build"
    publish = "dist"

[build.environment]
    HUGO_VERSION = "0.52"
    NODE_VERSION = "8"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "npm run build-preview"