backend:
  name: git-gateway
  
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: markdown }
    
  - name: "root"
    label: "Protected Pages"
    delete: false
    files:
      - name: "home"
        label: "Home Page"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Upper Heading", name: "upperHeading", widget: "string"}
