backend:
  name: git-gateway
  
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Upper Heading", name: "upperHeading", widget: "string"}
      - {label: "Publish date", name: "date", widget: "datetime"}
      - {label: "URL", name: "Page URL", widget: "string"}
      - label: "Menu"
        name: "menu"
        widget: "object"
        fields:
          - label: "Options"
            name: "main"
            widget: "object"
            fields:
              - {label: "Identifier", name: "identifier", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Weight", name: "weight", widget: "number"}
      - { label: "Body", name: "body", widget: markdown }
    
  - name: "root"
    label: "Protected Pages"
    delete: false
    files:
      - name: "home"
        label: "Home Page"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Upper Heading", name: "upperHeading", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "URL", name: "url", widget: "hidden"}
          - {label: "Menu", name: "menu", widget: "hidden"}
