backend:
  name: git-gateway
  
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  
  - label: "Page"
    name: "page"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
    files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: "Upper Heading", name: upperHeading, widget: string}
